name: dart_db_io
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  dart_firebase_admin: ^0.4.0
  meta: ^1.16.0
  fpdart: ^1.1.1
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0


dependency_overrides:
  dart_firebase_admin:
    git:
      url: https://github.com/ryota0624/dart_firebase_admin
      path: packages/dart_firebase_admin
      ref: bd4762dfe7f788831f941f6c9c3eb4da08cc47dd
